### ISSUE TITLE
Cannot install with meteor 1.3-beta.16

### ISSUE THREAD

**Issue by staskorz** [meteor/validated-method#42]
Errors while trying to install mdg:validated-method with meteor 1.3-beta.16

```
$ meteor add mdg:validated-method
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint ddp@1.2.2 is not satisfied by ddp 1.2.2-beta.16.
Constraints on package "ddp":
* ddp@=1.2.2-beta.16 <- top level
* ddp@1.2.2-beta.16 <- meteor-base 1.0.1-beta.16
* ddp@1.2.2-beta.16 <- livedata 1.0.15-beta.16 <- meteor-base 1.0.1-beta.16
* ddp@1.2.2-beta.16 <- autoupdate 1.2.5-beta.16 <- hot-code-push 1.0.1-beta.16 <- meteor-base 1.0.1-beta.16
* ddp@1.2.2-beta.16 <- mongo 1.1.4-beta.16
* ddp@1.2.2-beta.16 <- allow-deny 1.0.1-beta.16 <- mongo 1.1.4-beta.16
* ddp@1.2.2 <- mdg:validated-method 1.0.1
```

**Comment by stubailo** [comment]
Hm, looks like this was a bug in the release process for the 1.3 beta which resulted in the wrong version number for DDP.

I could publish a new version that relaxes the constraints, let me do that!

**Comment by benjamn** [comment]
Seems like `ddp@1.2.2-beta.16` definitely should satisfy the `ddp@1.2.2` constraint…

**Comment by stubailo** [comment]
No, because that version number says "This is a beta release of DDP 1.2.2" which isn't compatible with "This is the actual release of DDP 1.2.2". However, "The beta release of DDP 1.2.3" is considered to be above 1.2.2.

**Comment by stubailo** [comment]
@staskorz can you check if it works now with `mdg:validated-method` version `1.0.2`?

**Comment by staskorz** [comment]
@stubailo I've tried checking it, but always step on issue meteor/meteor#6448 that prevents my meteor project from running.

Following is the output:

```
$ meteor
[[[[[ C:\Users\stas\IdeaProjects\dummy-delete ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
W20160310-16:11:44.357(2)? (STDERR)
W20160310-16:11:44.358(2)? (STDERR) C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:313
W20160310-16:11:44.358(2)? (STDERR) }).run();
W20160310-16:11:44.358(2)? (STDERR)    ^
W20160310-16:11:44.359(2)? (STDERR) Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
W20160310-16:11:44.359(2)? (STDERR)     at Object.Npm.require (C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:193:17)
W20160310-16:11:44.359(2)? (STDERR)     at Meteor.startup (packages/meteor/fiber_helpers.js:17:1)
W20160310-16:11:44.359(2)? (STDERR)     at packages/meteor/fiber_helpers.js:182:1
W20160310-16:11:44.359(2)? (STDERR)     at C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\packages\meteor.js:1319:3
W20160310-16:11:44.359(2)? (STDERR)     at C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:272:10
W20160310-16:11:44.360(2)? (STDERR)     at Array.forEach (native)
W20160310-16:11:44.360(2)? (STDERR)     at Function._.each._.forEach (C:\Users\stas\AppData\Local\.meteor\packages\meteor-tool\1.1.13-beta.16\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160310-16:11:44.360(2)? (STDERR)     at C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:133:5
W20160310-16:11:46.709(2)? (STDERR)
W20160310-16:11:46.709(2)? (STDERR) C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:313
W20160310-16:11:46.709(2)? (STDERR) }).run();
W20160310-16:11:46.710(2)? (STDERR)    ^
W20160310-16:11:46.710(2)? (STDERR) Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
W20160310-16:11:46.710(2)? (STDERR)     at Object.Npm.require (C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:193:17)
W20160310-16:11:46.710(2)? (STDERR)     at Meteor.startup (packages/meteor/fiber_helpers.js:17:1)
W20160310-16:11:46.710(2)? (STDERR)     at packages/meteor/fiber_helpers.js:182:1
W20160310-16:11:46.710(2)? (STDERR)     at C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\packages\meteor.js:1319:3
W20160310-16:11:46.710(2)? (STDERR)     at C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:272:10
W20160310-16:11:46.710(2)? (STDERR)     at Array.forEach (native)
W20160310-16:11:46.710(2)? (STDERR)     at Function._.each._.forEach (C:\Users\stas\AppData\Local\.meteor\packages\meteor-tool\1.1.13-beta.16\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160310-16:11:46.711(2)? (STDERR)     at C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:133:5
=> Exited with code: 8
W20160310-16:11:48.686(2)? (STDERR)
W20160310-16:11:48.687(2)? (STDERR) C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:313
W20160310-16:11:48.687(2)? (STDERR) }).run();
W20160310-16:11:48.687(2)? (STDERR)    ^
W20160310-16:11:48.687(2)? (STDERR) Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
W20160310-16:11:48.687(2)? (STDERR)     at Object.Npm.require (C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:193:17)
W20160310-16:11:48.687(2)? (STDERR)     at Meteor.startup (packages/meteor/fiber_helpers.js:17:1)
W20160310-16:11:48.687(2)? (STDERR)     at packages/meteor/fiber_helpers.js:182:1
W20160310-16:11:48.687(2)? (STDERR)     at C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\packages\meteor.js:1319:3
W20160310-16:11:48.688(2)? (STDERR)     at C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:272:10
W20160310-16:11:48.688(2)? (STDERR)     at Array.forEach (native)
W20160310-16:11:48.688(2)? (STDERR)     at Function._.each._.forEach (C:\Users\stas\AppData\Local\.meteor\packages\meteor-tool\1.1.13-beta.16\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160310-16:11:48.688(2)? (STDERR)     at C:\Users\stas\IdeaProjects\dummy-delete\.meteor\local\build\programs\server\boot.js:133:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by michalmielczynski** [comment]
Same here, Windows 10, 64-bit:

```
W20160311-10:06:35.371(1)? (STDERR) Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
W20160311-10:06:35.372(1)? (STDERR)     at Object.Npm.require (C:\node\meteor\test-react-three\.meteor\local\build\programs\server\boot.js:193:17)
W20160311-10:06:35.372(1)? (STDERR)     at Meteor.startup (packages/meteor/fiber_helpers.js:17:1)
W20160311-10:06:35.372(1)? (STDERR)     at packages/meteor/fiber_helpers.js:182:1
W20160311-10:06:35.372(1)? (STDERR)     at C:\node\meteor\test-react-three\.meteor\local\build\programs\server\packages\meteor.js:1319:3
W20160311-10:06:35.372(1)? (STDERR)     at C:\node\meteor\test-react-three\.meteor\local\build\programs\server\boot.js:272:10
W20160311-10:06:35.372(1)? (STDERR)     at Array.forEach (native)
W20160311-10:06:35.372(1)? (STDERR)     at Function._.each._.forEach (C:\Users\John\AppData\Local\.meteor\packages\meteor-tool\1.1.13-beta.16\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)

W20160311-10:06:35.372(1)? (STDERR)     at C:\node\meteor\test-react-three\.meteor\local\build\programs\server\boot.js:133:5

```

**Comment by staskorz** [comment]
Tested with both 1.3-rc.3 and 1.3-rc.4 - works fine.

Many thanks for the quick resolution!
