### ISSUE TITLE
Bug in package tests: ReferenceError SimpleSchema is not defined

### ISSUE THREAD

**Issue by neil-s** [meteor/validated-method#48]
```
ReferenceError: SimpleSchema is not defined
at Package (validated-method-tests.js:3:17)
at C:\Tech\escalade\profile-meteor\.meteor\local\build\programs\server\packages\mdg_validated-method.js:366:4
at C:\Tech\escalade\profile-meteor\.meteor\local\build\programs\server\packages\mdg_validated-method.js:375:3
at C:\Tech\escalade\profile-meteor\.meteor\local\build\programs\server\boot.js:242:10
 at Array.forEach (native)
```

Environment:
Meteor 1.2.1
validated-method 1.1.0
simple-schema 1.5.3 (as an explicit dependency of the project)

Steps:
1. Take an old project, and install validated-method
2. Convert a vanilla Meteor Method to a validated-method
3. Run the project

I have SimpleSchema being used for validation in all the Template js files, so it is generally available to app code. This is Meteor 1.2.x, so all the code is eager-loaded and available everywhere. I'm guessing this has something to do with the fact that the error is from a package, so presumably the load order means that validated-method is getting loaded before simple-schema is available.

**Comment by stubailo** [comment]
Hmm, that's odd! Let me check.

**Comment by stubailo** [comment]
I'm confused - how does your app end up running the package tests for validated-method?

**Comment by neil-s** [comment]
Exactly what I'm wondering! I'm on Windows, just running the Meteor app as I normally would, with `meteor`. I looked inside the built code (`.meteor\local\build\programs\server\packages\mdg_validated-method.js:366`), and it does indeed have the tests code in there. So the `Package.onTest` block must somehow be getting executed despite not being in test mode. Have you tested this package on a Meteor 1.2 app?

(thanks for the insanely quick response time btw)

**Comment by stubailo** [comment]
that's weeeeeeird. I did publish with Meteor 1.3. can you load the package as a local package, and see if you get the same issue?

http://guide.meteor.com/using-packages.html#atmosphere-overriding

**Comment by neil-s** [comment]
I'm in the UK, so gonna pass out now, will get back to you tomorrow. I have a good feeling that you'll be able to reproduce the error by simply creating a new Meteor 1.2 app, installing the package, and running, even with no app code.

**Comment by stubailo** [comment]
Good idea.

**Comment by nathan-muir** [comment]
Just noticed this issue upgrading from `mdg:validated-method@0.2.3` to `mdg:validated-method@1.1.0`

A quick look at `~/.meteor/packages/mdg_validated-method/1.1.0/os.json` shows that something is funky - https://gist.github.com/nathan-muir/38ad3eb672bac9d3cdde4735c02e5d1f

Note that the same file for 1.0.0 doesn't have the block:

```
    {
      "type": "source",
      "extension": "js",
      "file": "os/validated-method-tests.js",
      "length": 4333,
      "offset": 0,
      "path": "validated-method-tests.js",
      "hash": "287fff0d535c06f9b100b641213d4950b049f743",
      "fileOptions": {
        "lazy": true
      }
    }

```

**Comment by stubailo** [comment]
@benjamn something to look at?

**Comment by namirsab** [comment]
@stubailo i'm having exactly the same issue.

```
ReferenceError: SimpleSchema is not defined
W20160510-16:51:06.372(2)? (STDERR)     at Package (validated-method-tests.js:3:17)
W20160510-16:51:06.372(2)? (STDERR)     at /tmp/meteor-test-run1jmifin/.meteor/local/build/programs/server/packages/mdg_validated-method.js:365:4
....
```

Also when upgrading to 1.1.0
I don't know if its related, but it's also impossible for me to add `mdg:validated-method` in it latest version for the tests, it has aproblem with `aldeed:simple-schema`:

```
error: Conflict: Constraint mdg:validation-error@0.5.0 is not satisfied by mdg:validation-error 0.2.0.
   Constraints on package "mdg:validation-error":
   * mdg:validation-error@0.5.0 <- local-test:qlp:qlp-multiple-validator-mixin 0.0.1
   * mdg:validation-error@0.2.0 <- aldeed:simple-schema 1.5.3 <- local-test:namirsab:mypackage 0.0.1
```

**Comment by kalubunda** [comment]
+1

**Comment by kalubunda** [comment]
Got the same error,  after adding some packages to my app.
anyone with a solution.?

C:\Users\ck19910410ck\AppData\Local.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
                        throw(ex);
                              ^
ReferenceError: SimpleSchema is not defined
    at Package (validated-method-tests.js:3:17)
    at C:\Users\ck19910410ck\ddtcwithoutbootstrap.meteor\local\build\programs\server\packages\mdg_validated-method.js:366:4
    at C:\Users\ck19910410ck\ddtcwithoutbootstrap.meteor\local\build\programs\server\packages\mdg_validated-method.js:375:3
    at C:\Users\ck19910410ck\ddtcwithoutbootstrap.meteor\local\build\programs\server\boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\ck19910410ck\AppData\Local.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    at C:\Users\ck19910410ck\ddtcwithoutbootstrap.meteor\local\build\programs\server\boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by Nexus7** [comment]
Having the same issue here with adding the validated-method package... With a Meteor 1.2.1 application we see the following on startup:

```
W20160627-10:19:01.739(8)? (STDERR)
W20160627-10:19:01.739(8)? (STDERR) /Users/Rick/.meteor/packages/meteor-tool/.1.1.10.1d3x4or++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160627-10:19:01.740(8)? (STDERR)                             throw(ex);
W20160627-10:19:01.740(8)? (STDERR)                                   ^
W20160627-10:19:01.759(8)? (STDERR) ReferenceError: SimpleSchema is not defined
W20160627-10:19:01.759(8)? (STDERR)     at Package (validated-method-tests.js:3:17)
```

Any ideas on how to resolve this or when a fix will come out? We really were hoping to start using the validated-method package to clean up our application....

Cheers
Rick
